/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCell: typeof import('./components/dialog/AddCell.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BoundaryLine: typeof import('./components/BoundaryLine.vue')['default']
    ConfirmDelete: typeof import('./components/ConfirmDelete.vue')['default']
    CustomPinLabelEditor: typeof import('./components/dialog/CustomPinLabelEditor.vue')['default']
    District: typeof import('./components/District.vue')['default']
    EarthAnimation: typeof import('./components/misc/EarthAnimation.vue')['default']
    FindClosest: typeof import('./components/FindClosest.vue')['default']
    GameCreator: typeof import('./components/game/GameCreator.vue')['default']
    GameSelector: typeof import('./components/game/GameSelector.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    History: typeof import('./components/dialog/History.vue')['default']
    LayerEditor: typeof import('./components/dialog/LayerEditor.vue')['default']
    Map: typeof import('./components/Map.vue')['default']
    MapActionButton: typeof import('./components/MapActionButton.vue')['default']
    MarkerEditor: typeof import('./components/dialog/MarkerEditor.vue')['default']
    Radar: typeof import('./components/Radar.vue')['default']
    RegionEditorMap: typeof import('./components/RegionEditorMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamJoiner: typeof import('./components/game/TeamJoiner.vue')['default']
    Thermometer: typeof import('./components/Thermometer.vue')['default']
    TimerView: typeof import('./components/TimerView.vue')['default']
  }
}
