/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    copy: typeof import('./components/LayerEditor copy.vue')['default']
    GameSelector: typeof import('./components/GameSelector.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LayerEditor: typeof import('./components/LayerEditor.vue')['default']
    Map: typeof import('./components/Map.vue')['default']
    MapActionButton: typeof import('./components/MapActionButton.vue')['default']
    Radar: typeof import('./components/Radar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
